name: CD

on:
  push:
    branches:
      [main]
      
permissions:
  contents: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Build image and push to docker hub
        uses: docker/build-push-action@v1.1.0
        with:
          username: estevan123
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: estevan123/argocd
          tags: ${{ github.sha }}, latest

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: kustomize
        uses: imranismail/setup-kustomize@v1
        with:
          kustomize_version: v3.6.1

      - name: updatek8s
        run: |
          cd k8s
          kustomize edit set image goapp=estevan123/argocd:${{ github.sha }}
          cat kustomization.yaml

      - name: commit
        run: |
          git config --global user.email "estevan123@gmail.com"
          git config --global user.name "Deploy Action"
          git commit -am "Update k8s resources"
         

      - name: push
        uses: ad-m/github-push-action@master